name: release

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  update-changelog:
    if: github.repository_owner == 'nuxt-contrib' && !contains(github.event.head_commit.message, 'v2.')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: latest
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - run: node ./scripts/update-changelog.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
